[package]
name = "trustfall-rustdoc"
version = "0.1.0"
edition = "2021"
authors = ["Predrag Gruevski <obi1kenobi82@gmail.com>"]
license = "Apache-2.0 OR MIT"
description = "Trustfall query adapter for rustdoc JSON data."
repository = "https://github.com/obi1kenobi/trustfall-rustdoc"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trustfall_core = "0.0.4"
rustdoc-types = "0.17.0"
serde_json = "1.0.82"
anyhow = "1.0.58"
serde = { version = "1.0.139", features = ["derive"] }
